## Sample Code & 作業內容


參考這次的進度，安裝好 OpenCV 之後分別顯示同一張圖片但個別是彩色 RGB 格式跟灰階 Grayscale 格式的圖

可以選擇電腦中任意圖片（建議選擇 .jpg, .jpeg, .png)

或是電腦視覺領域中知名的 [Lena](http://optipng.sourceforge.net/pngtech/img/lena.png) 圖皆可

## 範例

使用 Lena

1. 以彩色圖片顯示

2. 以灰階圖片顯示

In [1]:
import cv2

img_path = './lena.png'

# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# 以灰階圖片的方式載入
img_gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

# 為了要不斷顯示圖片，所以使用一個迴圈
while True:
    # 顯示彩圖
    cv2.imshow('bgr', img)
    # 顯示灰圖
    cv2.imshow('gray', img_gray)

    # 直到按下 ESC 鍵才會自動關閉視窗結束程式
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

## 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣 例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

> 將三個維度拆開 : 分別得到 B,G,R 三個 channel 的 array

## [OpenCV](https://docs.opencv.org/master/d3/df2/tutorial_py_basic_ops.html)

### Splitting and Merging Image Channels

Sometimes you will need to work separately on the B,G,R channels of an image. In this case, you need to split the BGR image into single channels. In other cases, you may need to join these individual channels to create a BGR image. You can do this simply by:

    b,g,r = cv2.split(img)
    img = cv2.merge((b,g,r))
    
    Or

    b = img[:,:,0]



In [2]:
import cv2
import numpy as np

img_path = './lena.png'

# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# 把圖片合併起來方便一起看
img_concat = np.hstack((img[:, :, 0], img[:, :, 1], img[:, :, 2]))


b,g,r = cv2.split(img)

# 為了要不斷顯示圖片，所以使用一個迴圈
while True:
    # 顯示彩圖
    cv2.imshow('bgr', img)
    cv2.imshow('bgr_split', img_concat)
    

    cv2.imshow('b', b)
    cv2.imshow('g', g)
    cv2.imshow('r', r)

    # 直到按下 ESC 鍵才會自動關閉視窗結束程式
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

In [3]:
img[:, :, 0]

array([[125, 125, 133, ..., 122, 110,  90],
       [125, 125, 133, ..., 122, 110,  90],
       [125, 125, 133, ..., 122, 110,  90],
       ...,
       [ 60,  60,  58, ...,  84,  76,  79],
       [ 57,  57,  62, ...,  79,  81,  81],
       [ 57,  57,  62, ...,  79,  81,  81]], dtype=uint8)

In [4]:
img[:, :, 1]

array([[137, 137, 137, ..., 148, 130,  99],
       [137, 137, 137, ..., 148, 130,  99],
       [137, 137, 137, ..., 148, 130,  99],
       ...,
       [ 18,  18,  27, ...,  73,  68,  62],
       [ 22,  22,  32, ...,  70,  71,  74],
       [ 22,  22,  32, ...,  70,  71,  74]], dtype=uint8)

In [5]:
img[:, :, 2]

array([[226, 226, 223, ..., 230, 221, 200],
       [226, 226, 223, ..., 230, 221, 200],
       [226, 226, 223, ..., 230, 221, 200],
       ...,
       [ 84,  84,  92, ..., 173, 172, 177],
       [ 82,  82,  96, ..., 179, 181, 185],
       [ 82,  82,  96, ..., 179, 181, 185]], dtype=uint8)